"""make_session_ids_nullable

Revision ID: 43604c781109
Revises: 46b3caba33a7
Create Date: 2026-06-16 20:42:58.037746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43604c781109'
down_revision: Union[str, Sequence[str], None] = '46b3caba33a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('race_sessions', 'circuit_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('race_sessions', 'driver_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('race_sessions', 'driver_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('race_sessions', 'circuit_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
