"""add_simulation_jobs

Revision ID: 46b3caba33a7
Revises: ff93dbc0c918
Create Date: 2026-06-16 11:29:25.583851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46b3caba33a7'
down_revision: Union[str, Sequence[str], None] = 'ff93dbc0c918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('result_id', sa.Uuid(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['simulation_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation_jobs')
    # ### end Alembic commands ###
