"""initial_schema

Revision ID: ff93dbc0c918
Revises: 
Create Date: 2026-06-16 11:17:29.702870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff93dbc0c918'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('laps', sa.Integer(), nullable=False),
    sa.Column('length_km', sa.Float(), nullable=False),
    sa.Column('avg_pit_loss', sa.Float(), nullable=False),
    sa.Column('characteristics', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('aggression', sa.Integer(), nullable=False),
    sa.Column('undercut_bias', sa.Integer(), nullable=False),
    sa.Column('risk_tolerance', sa.Integer(), nullable=False),
    sa.Column('tyre_focus', sa.Integer(), nullable=False),
    sa.Column('weather_adaptability', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drivers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('aggression', sa.Integer(), nullable=False),
    sa.Column('tyre_management', sa.Integer(), nullable=False),
    sa.Column('overtake_efficiency', sa.Integer(), nullable=False),
    sa.Column('wet_weather_skill', sa.Integer(), nullable=False),
    sa.Column('consistency', sa.Integer(), nullable=False),
    sa.Column('racecraft', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historical_races',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('circuit_id', sa.String(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.String(), nullable=False),
    sa.Column('winning_strategy', sa.String(), nullable=False),
    sa.Column('pit_stop_lap', sa.Integer(), nullable=False),
    sa.Column('starting_grid', sa.JSON(), nullable=False),
    sa.Column('weather', sa.String(), nullable=False),
    sa.Column('fastest_lap', sa.String(), nullable=True),
    sa.Column('winning_gap', sa.Float(), nullable=True),
    sa.Column('tyre_strategy', sa.JSON(), nullable=False),
    sa.Column('race_pace_metrics', sa.JSON(), nullable=False),
    sa.Column('safety_cars', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('race_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('circuit_id', sa.String(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('win_prob', sa.Float(), nullable=False),
    sa.Column('podium_prob', sa.Float(), nullable=False),
    sa.Column('avg_finish', sa.Float(), nullable=False),
    sa.Column('best_case', sa.Integer(), nullable=False),
    sa.Column('worst_case', sa.Integer(), nullable=False),
    sa.Column('iteration_count', sa.Integer(), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('raw_output', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['race_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_memory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('circuit_id', sa.String(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('success_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('outcome_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['race_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategy_memory')
    op.drop_table('simulation_results')
    op.drop_table('race_sessions')
    op.drop_table('historical_races')
    op.drop_table('drivers')
    op.drop_table('teams')
    op.drop_table('circuits')
    # ### end Alembic commands ###
