/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TelemetryRouteImport } from './routes/telemetry'
import { Route as StrategyLabRouteImport } from './routes/strategy-lab'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RaceCenterRouteImport } from './routes/race-center'
import { Route as MissionControlRouteImport } from './routes/mission-control'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiEngineerRouteImport } from './routes/ai-engineer'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TelemetryRoute = TelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyLabRoute = StrategyLabRouteImport.update({
  id: '/strategy-lab',
  path: '/strategy-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RaceCenterRoute = RaceCenterRouteImport.update({
  id: '/race-center',
  path: '/race-center',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionControlRoute = MissionControlRouteImport.update({
  id: '/mission-control',
  path: '/mission-control',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiEngineerRoute = AiEngineerRouteImport.update({
  id: '/ai-engineer',
  path: '/ai-engineer',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-engineer': typeof AiEngineerRoute
  '/analytics': typeof AnalyticsRoute
  '/mission-control': typeof MissionControlRoute
  '/race-center': typeof RaceCenterRoute
  '/settings': typeof SettingsRoute
  '/simulation': typeof SimulationRoute
  '/strategy-lab': typeof StrategyLabRoute
  '/telemetry': typeof TelemetryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-engineer': typeof AiEngineerRoute
  '/analytics': typeof AnalyticsRoute
  '/mission-control': typeof MissionControlRoute
  '/race-center': typeof RaceCenterRoute
  '/settings': typeof SettingsRoute
  '/simulation': typeof SimulationRoute
  '/strategy-lab': typeof StrategyLabRoute
  '/telemetry': typeof TelemetryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-engineer': typeof AiEngineerRoute
  '/analytics': typeof AnalyticsRoute
  '/mission-control': typeof MissionControlRoute
  '/race-center': typeof RaceCenterRoute
  '/settings': typeof SettingsRoute
  '/simulation': typeof SimulationRoute
  '/strategy-lab': typeof StrategyLabRoute
  '/telemetry': typeof TelemetryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-engineer'
    | '/analytics'
    | '/mission-control'
    | '/race-center'
    | '/settings'
    | '/simulation'
    | '/strategy-lab'
    | '/telemetry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-engineer'
    | '/analytics'
    | '/mission-control'
    | '/race-center'
    | '/settings'
    | '/simulation'
    | '/strategy-lab'
    | '/telemetry'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-engineer'
    | '/analytics'
    | '/mission-control'
    | '/race-center'
    | '/settings'
    | '/simulation'
    | '/strategy-lab'
    | '/telemetry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiEngineerRoute: typeof AiEngineerRoute
  AnalyticsRoute: typeof AnalyticsRoute
  MissionControlRoute: typeof MissionControlRoute
  RaceCenterRoute: typeof RaceCenterRoute
  SettingsRoute: typeof SettingsRoute
  SimulationRoute: typeof SimulationRoute
  StrategyLabRoute: typeof StrategyLabRoute
  TelemetryRoute: typeof TelemetryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/telemetry': {
      id: '/telemetry'
      path: '/telemetry'
      fullPath: '/telemetry'
      preLoaderRoute: typeof TelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy-lab': {
      id: '/strategy-lab'
      path: '/strategy-lab'
      fullPath: '/strategy-lab'
      preLoaderRoute: typeof StrategyLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/race-center': {
      id: '/race-center'
      path: '/race-center'
      fullPath: '/race-center'
      preLoaderRoute: typeof RaceCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-control': {
      id: '/mission-control'
      path: '/mission-control'
      fullPath: '/mission-control'
      preLoaderRoute: typeof MissionControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-engineer': {
      id: '/ai-engineer'
      path: '/ai-engineer'
      fullPath: '/ai-engineer'
      preLoaderRoute: typeof AiEngineerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiEngineerRoute: AiEngineerRoute,
  AnalyticsRoute: AnalyticsRoute,
  MissionControlRoute: MissionControlRoute,
  RaceCenterRoute: RaceCenterRoute,
  SettingsRoute: SettingsRoute,
  SimulationRoute: SimulationRoute,
  StrategyLabRoute: StrategyLabRoute,
  TelemetryRoute: TelemetryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
