export const CIRCUITS = [
  {
    name: "Monaco",
    flag: "MC",
    pitLoss: 22.4,
    deg: "Low",
    degRate: 0.8,
    laps: 78,
    sectors: [28.4, 33.2, 21.8],
  },
  {
    name: "Silverstone",
    flag: "GB",
    pitLoss: 19.8,
    deg: "High",
    degRate: 1.4,
    laps: 52,
    sectors: [27.1, 31.6, 19.4],
  },
  {
    name: "Monza",
    flag: "IT",
    pitLoss: 21.1,
    deg: "Medium",
    degRate: 0.9,
    laps: 53,
    sectors: [26.8, 30.2, 18.6],
  },
  {
    name: "Bahrain",
    flag: "BH",
    pitLoss: 22.9,
    deg: "High",
    degRate: 1.3,
    laps: 57,
    sectors: [28.2, 32.4, 20.1],
  },
  {
    name: "Singapore",
    flag: "SG",
    pitLoss: 27.3,
    deg: "Medium",
    degRate: 1.1,
    laps: 62,
    sectors: [29.8, 34.2, 22.4],
  },
  {
    name: "Spa",
    flag: "BE",
    pitLoss: 20.6,
    deg: "Medium",
    degRate: 1.0,
    laps: 44,
    sectors: [27.4, 32.8, 19.6],
  },
  {
    name: "Suzuka",
    flag: "JP",
    pitLoss: 21.4,
    deg: "High",
    degRate: 1.2,
    laps: 53,
    sectors: [26.2, 31.4, 18.8],
  },
  {
    name: "Interlagos",
    flag: "BR",
    pitLoss: 19.2,
    deg: "Medium",
    degRate: 1.0,
    laps: 71,
    sectors: [25.8, 30.6, 18.2],
  },
  {
    name: "Abu Dhabi",
    flag: "AE",
    pitLoss: 21.8,
    deg: "Low",
    degRate: 0.8,
    laps: 58,
    sectors: [27.6, 32.2, 20.4],
  },
  {
    name: "Miami",
    flag: "US",
    pitLoss: 20.9,
    deg: "Medium",
    degRate: 1.0,
    laps: 57,
    sectors: [27.2, 31.8, 19.6],
  },
  {
    name: "Las Vegas",
    flag: "US",
    pitLoss: 22.1,
    deg: "Low",
    degRate: 0.7,
    laps: 50,
    sectors: [26.4, 30.8, 18.4],
  },
  {
    name: "Qatar",
    flag: "QA",
    pitLoss: 23.0,
    deg: "High",
    degRate: 1.5,
    laps: 57,
    sectors: [28.6, 33.4, 21.2],
  },
  {
    name: "Imola",
    flag: "IT",
    pitLoss: 26.8,
    deg: "Medium",
    degRate: 1.1,
    laps: 63,
    sectors: [28.4, 33.6, 21.8],
  },
  {
    name: "Zandvoort",
    flag: "NL",
    pitLoss: 22.6,
    deg: "High",
    degRate: 1.3,
    laps: 72,
    sectors: [27.8, 32.4, 20.2],
  },
  {
    name: "COTA",
    flag: "US",
    pitLoss: 21.6,
    deg: "Medium",
    degRate: 1.1,
    laps: 56,
    sectors: [27.4, 32.6, 19.8],
  },
  {
    name: "Jeddah",
    flag: "SA",
    pitLoss: 19.4,
    deg: "Low",
    degRate: 0.9,
    laps: 50,
    sectors: [26.6, 30.4, 18.8],
  },
  {
    name: "Melbourne",
    flag: "AU",
    pitLoss: 21.2,
    deg: "Medium",
    degRate: 1.0,
    laps: 58,
    sectors: [27.2, 31.8, 19.4],
  },
  {
    name: "Montreal",
    flag: "CA",
    pitLoss: 20.4,
    deg: "Medium",
    degRate: 1.0,
    laps: 70,
    sectors: [26.8, 31.2, 19.0],
  },
  {
    name: "Hungaroring",
    flag: "HU",
    pitLoss: 22.2,
    deg: "Medium",
    degRate: 1.1,
    laps: 70,
    sectors: [28.2, 33.0, 21.0],
  },
  {
    name: "Baku",
    flag: "AZ",
    pitLoss: 20.8,
    deg: "Low",
    degRate: 0.8,
    laps: 51,
    sectors: [27.0, 31.6, 19.2],
  },
];

export const COMPOUNDS = [
  {
    id: "SOFT",
    color: "#EF4444",
    label: "SOFT",
    shortLabel: "S",
    degRate: 0.12,
    gripBase: 98.4,
    stintWindow: [8, 18],
  },
  {
    id: "MEDIUM",
    color: "#F59E0B",
    label: "MED",
    shortLabel: "M",
    degRate: 0.08,
    gripBase: 96.8,
    stintWindow: [14, 28],
  },
  {
    id: "HARD",
    color: "#6B7280",
    label: "HARD",
    shortLabel: "H",
    degRate: 0.05,
    gripBase: 95.2,
    stintWindow: [22, 40],
  },
  {
    id: "INTER",
    color: "#10B981",
    label: "INTER",
    shortLabel: "I",
    degRate: 0.15,
    gripBase: 94.0,
    stintWindow: [10, 20],
  },
  {
    id: "WET",
    color: "#0EA5E9",
    label: "WET",
    shortLabel: "W",
    degRate: 0.18,
    gripBase: 92.0,
    stintWindow: [8, 16],
  },
] as const;

export type CompoundId = (typeof COMPOUNDS)[number]["id"];

export const WEATHER_OPTIONS = [
  "Dry",
  "Light Rain",
  "Heavy Rain",
  "Changeable",
] as const;
export type WeatherOption = (typeof WEATHER_OPTIONS)[number];

export function genDegCurve(seed = Math.random()) {
  return Array.from({ length: 30 }, (_, i) => ({
    lap: i + 1,
    soft: Math.max(20, 100 - i * (3 + seed * 0.5) - Math.random() * 4),
    medium: Math.max(30, 100 - i * (1.8 + seed * 0.3) - Math.random() * 3),
    hard: Math.max(45, 100 - i * (1.1 + seed * 0.2) - Math.random() * 2),
  }));
}
